create or replace view MARKETING_DATA_QUALITY_DB.STAGING.STG_CONVERSIONS(
	CONVERSION_ID,
	USER_ID,
	CONVERSION_TIME,
	CONVERSION_TYPE,
	REVENUE
) as

SELECT
CONVERSION_ID,
USER_ID,
CONVERSION_TIME,
LOWER(TRIM(CONVERSION_TYPE)) AS CONVERSION_TYPE,
REVENUE
FROM RAW.CONVERSIONS;
