create or replace view MARKETING_DATA_QUALITY_DB.STAGING.STG_CAMPAIGNS(
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	CHANNEL,
	CAMPAIGN_START_DATE,
	CAMPAIGN_END_DATE,
	CAMPAIGN_OBJECTIVE,
	BUDGET
) as

SELECT
CAMPAIGN_ID,
TRIM(CAMPAIGN_NAME) AS CAMPAIGN_NAME,
LOWER(TRIM(CHANNEL)) AS CHANNEL,
CAMPAIGN_START_DATE,
CAMPAIGN_END_DATE,
LOWER(TRIM(CAMPAIGN_OBJECTIVE)) AS CAMPAIGN_OBJECTIVE,
BUDGET
FROM RAW.CAMPAIGNS;
