create or replace view MARKETING_DATA_QUALITY_DB.STAGING.STG_CUSTOMERS(
	USER_ID,
	SIGNUP_DATE,
	COUNTRY,
	DEVICE_TYPE
) as

SELECT
USER_ID,
SIGNUP_DATE,
UPPER(TRIM(COUNTRY)) AS COUNTRY,
LOWER(TRIM(DEVICE_TYPE)) AS DEVICE_TYPE
FROM RAW.CUSTOMERS;
