create or replace view MARKETING_DATA_QUALITY_DB.STAGING.STG_MARKETING_TOUCHPOINTS(
	TOUCHPOINT_ID,
	USER_ID,
	CAMPAIGN_ID,
	CHANNEL,
	TOUCHPOINT_TIME,
	EVENT_TYPE,
	DEVICE_TYPE
) as

SELECT
TOUCHPOINT_ID,
USER_ID,
CAMPAIGN_ID,
LOWER(TRIM(CHANNEL)) AS CHANNEL,
TOUCHPOINT_TIME,
LOWER(TRIM(EVENT_TYPE)) AS EVENT_TYPE,
LOWER(TRIM(DEVICE_TYPE)) AS DEVICE_TYPE
FROM RAW.MARKETING_TOUCHPOINTS;
