create or replace view MARKETING_DATA_QUALITY_DB.QUALITY.INT_FRESHNESS_CHECKS(
	TABLE_NAME,
	DATE_COLUMN,
	LATEST_RECORD_DATE,
	DAYS_DELAYED,
	STATUS
) as

SELECT
'STG_CAMPAIGNS' AS TABLE_NAME,
'CAMPAIGN_END_DATE' AS DATE_COLUMN,
MAX(CAMPAIGN_END_DATE) AS LATEST_RECORD_DATE,
DATEDIFF('day', MAX(CAMPAIGN_END_DATE), '2026-04-15') AS DAYS_DELAYED,
CASE
WHEN DATEDIFF('day', MAX(CAMPAIGN_END_DATE), '2026-04-15') <= 30 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CAMPAIGNS

UNION ALL

SELECT
'STG_CUSTOMERS' AS TABLE_NAME,
'SIGNUP_DATE' AS DATE_COLUMN,
MAX(SIGNUP_DATE) AS LATEST_RECORD_DATE,
DATEDIFF('day', MAX(SIGNUP_DATE), '2026-04-15') AS DAYS_DELAYED,
CASE
WHEN DATEDIFF('day', MAX(SIGNUP_DATE), '2026-04-15') <= 30 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CUSTOMERS

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
'TOUCHPOINT_TIME' AS DATE_COLUMN,
CAST(MAX(TOUCHPOINT_TIME) AS DATE) AS LATEST_RECORD_DATE,
DATEDIFF('day', CAST(MAX(TOUCHPOINT_TIME) AS DATE), '2026-04-15') AS DAYS_DELAYED,
CASE
WHEN DATEDIFF('day', CAST(MAX(TOUCHPOINT_TIME) AS DATE), '2026-04-15') <= 30 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS

UNION ALL

SELECT
'STG_CONVERSIONS' AS TABLE_NAME,
'CONVERSION_TIME' AS DATE_COLUMN,
CAST(MAX(CONVERSION_TIME) AS DATE) AS LATEST_RECORD_DATE,
DATEDIFF('day', CAST(MAX(CONVERSION_TIME) AS DATE), '2026-04-15') AS DAYS_DELAYED,
CASE
WHEN DATEDIFF('day', CAST(MAX(CONVERSION_TIME) AS DATE), '2026-04-15') <= 30 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CONVERSIONS

UNION ALL

SELECT
'STG_AD_SPEND' AS TABLE_NAME,
'DATE' AS DATE_COLUMN,
MAX(DATE) AS LATEST_RECORD_DATE,
DATEDIFF('day', MAX(DATE), '2026-04-15') AS DAYS_DELAYED,
CASE
WHEN DATEDIFF('day', MAX(DATE), '2026-04-15') <= 30 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_AD_SPEND;
