create or replace view MARKETING_DATA_QUALITY_DB.QUALITY.INT_REFERENTIAL_INTEGRITY_CHECKS(
	CHECK_NAME,
	SOURCE_TABLE,
	REFERENCE_TABLE,
	KEY_COLUMN,
	MISSING_KEY_VALUE,
	FAILED_RECORDS,
	STATUS
) as

SELECT
'TOUCHPOINTS_TO_CAMPAIGNS' AS CHECK_NAME,
'STG_MARKETING_TOUCHPOINTS' AS SOURCE_TABLE,
'STG_CAMPAIGNS' AS REFERENCE_TABLE,
'CAMPAIGN_ID' AS KEY_COLUMN,
t.CAMPAIGN_ID AS MISSING_KEY_VALUE,
COUNT(1) AS FAILED_RECORDS,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS t
LEFT JOIN STAGING.STG_CAMPAIGNS c
ON t.CAMPAIGN_ID = c.CAMPAIGN_ID
WHERE c.CAMPAIGN_ID IS NULL
GROUP BY t.CAMPAIGN_ID

UNION ALL

SELECT
'AD_SPEND_TO_CAMPAIGNS' AS CHECK_NAME,
'STG_AD_SPEND' AS SOURCE_TABLE,
'STG_CAMPAIGNS' AS REFERENCE_TABLE,
'CAMPAIGN_ID' AS KEY_COLUMN,
a.CAMPAIGN_ID AS MISSING_KEY_VALUE,
COUNT(1) AS FAILED_RECORDS,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_AD_SPEND a
LEFT JOIN STAGING.STG_CAMPAIGNS c
ON a.CAMPAIGN_ID = c.CAMPAIGN_ID
WHERE c.CAMPAIGN_ID IS NULL
GROUP BY a.CAMPAIGN_ID

UNION ALL

SELECT
'TOUCHPOINTS_TO_CUSTOMERS' AS CHECK_NAME,
'STG_MARKETING_TOUCHPOINTS' AS SOURCE_TABLE,
'STG_CUSTOMERS' AS REFERENCE_TABLE,
'USER_ID' AS KEY_COLUMN,
t.USER_ID AS MISSING_KEY_VALUE,
COUNT(1) AS FAILED_RECORDS,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS t
LEFT JOIN STAGING.STG_CUSTOMERS c
ON t.USER_ID = c.USER_ID
WHERE c.USER_ID IS NULL
GROUP BY t.USER_ID

UNION ALL

SELECT
'CONVERSIONS_TO_CUSTOMERS' AS CHECK_NAME,
'STG_CONVERSIONS' AS SOURCE_TABLE,
'STG_CUSTOMERS' AS REFERENCE_TABLE,
'USER_ID' AS KEY_COLUMN,
cn.USER_ID AS MISSING_KEY_VALUE,
COUNT(1) AS FAILED_RECORDS,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_CONVERSIONS cn
LEFT JOIN STAGING.STG_CUSTOMERS c
ON cn.USER_ID = c.USER_ID
WHERE c.USER_ID IS NULL
GROUP BY cn.USER_ID;
