create or replace view MARKETING_DATA_QUALITY_DB.QUALITY.INT_NULL_CHECKS(
	TABLE_NAME,
	COLUMN_NAME,
	NULL_COUNT,
	STATUS
) as

SELECT
'STG_CAMPAIGNS' AS TABLE_NAME,
'CAMPAIGN_ID' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CAMPAIGNS
WHERE CAMPAIGN_ID IS NULL

UNION ALL

SELECT
'STG_CAMPAIGNS' AS TABLE_NAME,
'CHANNEL' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CAMPAIGNS
WHERE CHANNEL IS NULL

UNION ALL

SELECT
'STG_CUSTOMERS' AS TABLE_NAME,
'USER_ID' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CUSTOMERS
WHERE USER_ID IS NULL

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
'TOUCHPOINT_ID' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS
WHERE TOUCHPOINT_ID IS NULL

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
'USER_ID' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS
WHERE USER_ID IS NULL

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
'CAMPAIGN_ID' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS
WHERE CAMPAIGN_ID IS NULL

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
'CHANNEL' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS
WHERE CHANNEL IS NULL

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
'EVENT_TYPE' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS
WHERE EVENT_TYPE IS NULL

UNION ALL

SELECT
'STG_CONVERSIONS' AS TABLE_NAME,
'CONVERSION_ID' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CONVERSIONS
WHERE CONVERSION_ID IS NULL

UNION ALL

SELECT
'STG_CONVERSIONS' AS TABLE_NAME,
'USER_ID' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CONVERSIONS
WHERE USER_ID IS NULL

UNION ALL

SELECT
'STG_CONVERSIONS' AS TABLE_NAME,
'CONVERSION_TYPE' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CONVERSIONS
WHERE CONVERSION_TYPE IS NULL

UNION ALL

SELECT
'STG_CONVERSIONS' AS TABLE_NAME,
'REVENUE' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_CONVERSIONS
WHERE REVENUE IS NULL

UNION ALL

SELECT
'STG_AD_SPEND' AS TABLE_NAME,
'CAMPAIGN_ID' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_AD_SPEND
WHERE CAMPAIGN_ID IS NULL

UNION ALL

SELECT
'STG_AD_SPEND' AS TABLE_NAME,
'CHANNEL' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_AD_SPEND
WHERE CHANNEL IS NULL

UNION ALL

SELECT
'STG_AD_SPEND' AS TABLE_NAME,
'SPEND' AS COLUMN_NAME,
COUNT(1) AS NULL_COUNT,
CASE
WHEN COUNT(1) = 0 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM STAGING.STG_AD_SPEND
WHERE SPEND IS NULL;
