create or replace view MARKETING_DATA_QUALITY_DB.QUALITY.INT_REVENUE_RECONCILIATION(
	CHECK_NAME,
	TOTAL_SOURCE_REVENUE,
	TOTAL_DAILY_REVENUE,
	REVENUE_DIFFERENCE,
	TOTAL_CONVERSION_ROWS,
	NULL_REVENUE_ROWS,
	NEGATIVE_REVENUE_ROWS,
	STATUS
) as

WITH source_revenue AS (

SELECT
ROUND(SUM(REVENUE), 2) AS TOTAL_SOURCE_REVENUE,
COUNT(1) AS TOTAL_CONVERSION_ROWS,
COUNT(CASE WHEN REVENUE IS NULL THEN 1 END) AS NULL_REVENUE_ROWS,
COUNT(CASE WHEN REVENUE < 0 THEN 1 END) AS NEGATIVE_REVENUE_ROWS
FROM STAGING.STG_CONVERSIONS

),

daily_revenue AS (

SELECT
CAST(CONVERSION_TIME AS DATE) AS CONVERSION_DATE,
ROUND(SUM(REVENUE), 2) AS DAILY_REVENUE
FROM STAGING.STG_CONVERSIONS
GROUP BY CAST(CONVERSION_TIME AS DATE)

),

daily_revenue_summary AS (

SELECT
ROUND(SUM(DAILY_REVENUE), 2) AS TOTAL_DAILY_REVENUE
FROM daily_revenue

)

SELECT
'CONVERSION_REVENUE_RECONCILIATION' AS CHECK_NAME,

s.TOTAL_SOURCE_REVENUE,
d.TOTAL_DAILY_REVENUE,

ROUND(
s.TOTAL_SOURCE_REVENUE - d.TOTAL_DAILY_REVENUE,
2
) AS REVENUE_DIFFERENCE,

s.TOTAL_CONVERSION_ROWS,
s.NULL_REVENUE_ROWS,
s.NEGATIVE_REVENUE_ROWS,

CASE
WHEN ROUND(s.TOTAL_SOURCE_REVENUE - d.TOTAL_DAILY_REVENUE, 2) = 0
AND s.NULL_REVENUE_ROWS = 0
AND s.NEGATIVE_REVENUE_ROWS = 0
THEN 'PASS'
ELSE 'FAIL'
END AS STATUS

FROM source_revenue s
CROSS JOIN daily_revenue_summary d;
