create or replace view MARKETING_DATA_QUALITY_DB.QUALITY.INT_VOLUME_ANOMALY_CHECKS(
	TABLE_NAME,
	ACTUAL_ROW_COUNT,
	EXPECTED_ROW_COUNT,
	VARIANCE_PERCENT,
	STATUS
) as

WITH row_counts AS (

SELECT
'STG_CAMPAIGNS' AS TABLE_NAME,
COUNT(1) AS ACTUAL_ROW_COUNT,
25 AS EXPECTED_ROW_COUNT
FROM STAGING.STG_CAMPAIGNS

UNION ALL

SELECT
'STG_CUSTOMERS' AS TABLE_NAME,
COUNT(1) AS ACTUAL_ROW_COUNT,
500 AS EXPECTED_ROW_COUNT
FROM STAGING.STG_CUSTOMERS

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
COUNT(1) AS ACTUAL_ROW_COUNT,
5500 AS EXPECTED_ROW_COUNT
FROM STAGING.STG_MARKETING_TOUCHPOINTS

UNION ALL

SELECT
'STG_CONVERSIONS' AS TABLE_NAME,
COUNT(1) AS ACTUAL_ROW_COUNT,
800 AS EXPECTED_ROW_COUNT
FROM STAGING.STG_CONVERSIONS

UNION ALL

SELECT
'STG_AD_SPEND' AS TABLE_NAME,
COUNT(1) AS ACTUAL_ROW_COUNT,
2250 AS EXPECTED_ROW_COUNT
FROM STAGING.STG_AD_SPEND
)

SELECT
TABLE_NAME,
ACTUAL_ROW_COUNT,
EXPECTED_ROW_COUNT,

ROUND(
((ACTUAL_ROW_COUNT - EXPECTED_ROW_COUNT) / NULLIF(EXPECTED_ROW_COUNT, 0)) * 100,
2
) AS VARIANCE_PERCENT,

CASE
WHEN ABS(
((ACTUAL_ROW_COUNT - EXPECTED_ROW_COUNT) / NULLIF(EXPECTED_ROW_COUNT, 0)) * 100
) <= 20 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS

FROM row_counts;
