create or replace view MARKETING_DATA_QUALITY_DB.QUALITY.INT_ACCEPTED_VALUES_CHECKS(
	TABLE_NAME,
	COLUMN_NAME,
	INVALID_VALUE,
	INVALID_COUNT,
	STATUS
) as

SELECT
'STG_CAMPAIGNS' AS TABLE_NAME,
'CHANNEL' AS COLUMN_NAME,
CHANNEL AS INVALID_VALUE,
COUNT(1) AS INVALID_COUNT,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_CAMPAIGNS
WHERE CHANNEL NOT IN ('meta', 'google', 'affiliate', 'email', 'app')
GROUP BY CHANNEL

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
'CHANNEL' AS COLUMN_NAME,
CHANNEL AS INVALID_VALUE,
COUNT(1) AS INVALID_COUNT,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS
WHERE CHANNEL NOT IN ('meta', 'google', 'affiliate', 'email', 'app')
GROUP BY CHANNEL

UNION ALL

SELECT
'STG_AD_SPEND' AS TABLE_NAME,
'CHANNEL' AS COLUMN_NAME,
CHANNEL AS INVALID_VALUE,
COUNT(1) AS INVALID_COUNT,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_AD_SPEND
WHERE CHANNEL NOT IN ('meta', 'google', 'affiliate', 'email', 'app')
GROUP BY CHANNEL

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
'EVENT_TYPE' AS COLUMN_NAME,
EVENT_TYPE AS INVALID_VALUE,
COUNT(1) AS INVALID_COUNT,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS
WHERE EVENT_TYPE NOT IN ('impression', 'click', 'landing_page_visit', 'app_install')
GROUP BY EVENT_TYPE

UNION ALL

SELECT
'STG_CONVERSIONS' AS TABLE_NAME,
'CONVERSION_TYPE' AS COLUMN_NAME,
CONVERSION_TYPE AS INVALID_VALUE,
COUNT(1) AS INVALID_COUNT,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_CONVERSIONS
WHERE CONVERSION_TYPE NOT IN ('signup', 'deposit', 'purchase', 'subscription')
GROUP BY CONVERSION_TYPE

UNION ALL

SELECT
'STG_CUSTOMERS' AS TABLE_NAME,
'DEVICE_TYPE' AS COLUMN_NAME,
DEVICE_TYPE AS INVALID_VALUE,
COUNT(1) AS INVALID_COUNT,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_CUSTOMERS
WHERE DEVICE_TYPE NOT IN ('mobile', 'desktop', 'tablet')
GROUP BY DEVICE_TYPE

UNION ALL

SELECT
'STG_CAMPAIGNS' AS TABLE_NAME,
'CAMPAIGN_OBJECTIVE' AS COLUMN_NAME,
CAMPAIGN_OBJECTIVE AS INVALID_VALUE,
COUNT(1) AS INVALID_COUNT,
CASE
WHEN COUNT(1) > 0 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_CAMPAIGNS
WHERE CAMPAIGN_OBJECTIVE NOT IN (
'acquisition',
'retention',
'reactivation',
'deposit_growth',
'app_engagement'
)
GROUP BY CAMPAIGN_OBJECTIVE;
