create or replace view MARKETING_DATA_QUALITY_DB.QUALITY.INT_DUPLICATE_CHECKS(
	TABLE_NAME,
	KEY_COLUMN,
	DUPLICATE_VALUE,
	DUPLICATE_COUNT,
	STATUS
) as

SELECT
'STG_CAMPAIGNS' AS TABLE_NAME,
'CAMPAIGN_ID' AS KEY_COLUMN,
CAMPAIGN_ID AS DUPLICATE_VALUE,
COUNT(1) AS DUPLICATE_COUNT,
CASE
WHEN COUNT(1) > 1 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_CAMPAIGNS
GROUP BY CAMPAIGN_ID
HAVING COUNT(1) > 1

UNION ALL

SELECT
'STG_CUSTOMERS' AS TABLE_NAME,
'USER_ID' AS KEY_COLUMN,
USER_ID AS DUPLICATE_VALUE,
COUNT(1) AS DUPLICATE_COUNT,
CASE
WHEN COUNT(1) > 1 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_CUSTOMERS
GROUP BY USER_ID
HAVING COUNT(1) > 1

UNION ALL

SELECT
'STG_MARKETING_TOUCHPOINTS' AS TABLE_NAME,
'TOUCHPOINT_ID' AS KEY_COLUMN,
TOUCHPOINT_ID AS DUPLICATE_VALUE,
COUNT(1) AS DUPLICATE_COUNT,
CASE
WHEN COUNT(1) > 1 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_MARKETING_TOUCHPOINTS
GROUP BY TOUCHPOINT_ID
HAVING COUNT(1) > 1

UNION ALL

SELECT
'STG_CONVERSIONS' AS TABLE_NAME,
'CONVERSION_ID' AS KEY_COLUMN,
CONVERSION_ID AS DUPLICATE_VALUE,
COUNT(1) AS DUPLICATE_COUNT,
CASE
WHEN COUNT(1) > 1 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_CONVERSIONS
GROUP BY CONVERSION_ID
HAVING COUNT(1) > 1

UNION ALL

SELECT
'STG_AD_SPEND' AS TABLE_NAME,
'CAMPAIGN_ID + DATE + CHANNEL' AS KEY_COLUMN,
CAMPAIGN_ID || ' | ' || DATE || ' | ' || CHANNEL AS DUPLICATE_VALUE,
COUNT(1) AS DUPLICATE_COUNT,
CASE
WHEN COUNT(1) > 1 THEN 'FAIL'
ELSE 'PASS'
END AS STATUS
FROM STAGING.STG_AD_SPEND
GROUP BY
CAMPAIGN_ID,
DATE,
CHANNEL
HAVING COUNT(1) > 1;
