SELECT
ROUND(AVG(QUALITY_SCORE_PERCENT), 2) AS OVERALL_DATA_QUALITY_SCORE,

CASE
WHEN ROUND(AVG(QUALITY_SCORE_PERCENT), 2) >= 95
THEN 'EXCELLENT'

WHEN ROUND(AVG(QUALITY_SCORE_PERCENT), 2) >= 85
THEN 'GOOD'

WHEN ROUND(AVG(QUALITY_SCORE_PERCENT), 2) >= 70
THEN 'WARNING'

ELSE 'CRITICAL'
END AS OVERALL_QUALITY_STATUS

FROM ANALYTICS.DATA_QUALITY_SCORECARD;

