create or replace TABLE MARKETING_DATA_QUALITY_DB.ANALYTICS.DATA_QUALITY_SCORECARD (
	QUALITY_DIMENSION VARCHAR(16),
	TEST_NAME VARCHAR(27),
	TOTAL_CHECKS NUMBER(18,0),
	PASSED_CHECKS NUMBER(13,0),
	FAILED_CHECKS NUMBER(13,0),
	QUALITY_SCORE_PERCENT NUMBER(23,2),
	QUALITY_STATUS VARCHAR(9)
);
