create or replace TABLE MARKETING_DATA_QUALITY_DB.ANALYTICS.FCT_ALERT_SUMMARY (
	TEST_NAME VARCHAR(27),
	ALERT_SEVERITY VARCHAR(6),
	TOTAL_ALERTS NUMBER(18,0),
	LATEST_ALERT_TIMESTAMP TIMESTAMP_LTZ(9)
);
