create or replace TABLE MARKETING_DATA_QUALITY_DB.ANALYTICS.FCT_PIPELINE_HEALTH (
	TOTAL_TESTS NUMBER(18,0),
	PASSED_TESTS NUMBER(13,0),
	FAILED_TESTS NUMBER(13,0),
	QUALITY_SCORE NUMBER(23,2),
	PIPELINE_STATUS VARCHAR(8),
	HEALTH_CHECK_TIMESTAMP TIMESTAMP_LTZ(9)
);
