create or replace TABLE MARKETING_DATA_QUALITY_DB.ANALYTICS.FCT_DATA_FRESHNESS (
	TABLE_NAME VARCHAR(25),
	DATE_COLUMN VARCHAR(17),
	LATEST_RECORD_DATE DATE,
	DAYS_DELAYED NUMBER(9,0),
	FRESHNESS_STATUS VARCHAR(4),
	DATA_FRESHNESS_CATEGORY VARCHAR(5),
	CHECK_TIMESTAMP TIMESTAMP_LTZ(9)
);
